[project]
name = "multi-rater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nibabel>=5.3.2",
    "scipy>=1.16.1",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
